version: "3.8"
services:
  minio:
    image: minio/minio:RELEASE.2024-06-04T19-20-08Z.fips
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  mcconfig:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ./config:/config
    entrypoint: ["/bin/sh","/config/user_bucket_policy.sh"]
volumes:
  minio-data:

