version: "3.8"
services:
  y2rss_api:
    env_file:
      - .env
    container_name: y2rss_api
    image: docker.io/gepi/y2rss_api:0.0.2
    networks:
      - db_y2rss_network
    restart: unless-stopped
#    ports:
#      - "8081:8081"
networks:
  db_y2rss_network:
    external: true